//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shiftim
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        public string email { get; set; }
        public System.DateTime date { get; set; }
        public string day { get; set; }
        public string myShift { get; set; }
        public string comments { get; set; }
        public string approve { get; set; }
    }
}
